import http from "k6/http";
import { check, sleep } from "k6";

export const options = {
  scenarios: {
    notepad_load: {
      executor: "shared-iterations",
      vus: 100,           // 100 virtual user mengirim request secara paralel
      iterations: 50000,  // total 50.000 request yang akan dikirim
      maxDuration: "5m",  // batas waktu maksimal kalau ternyata lambat sekali
    },
  },
};

// Ganti dengan ID user yang BENAR-BENAR ada di database kamu (dari Step 2)
const VALID_USER_IDS = [1, 3, 4, 5, 6];

export default function () {
  // 80% request pakai user_id valid, 20% pakai user_id ngasal (untuk test validasi gagal)
  const isValidUser = Math.random() < 0.8;
  const userId = isValidUser
    ? VALID_USER_IDS[Math.floor(Math.random() * VALID_USER_IDS.length)]
    : Math.floor(Math.random() * 100000) + 90000; // pasti tidak ada di database

  const payload = JSON.stringify({
    user_id: userId,
    title: `Load test notepad ${__ITER}`,
    content: `Generated by k6 at iteration ${__ITER}`,
  });

  const params = {
    headers: { "Content-Type": "application/json" },
  };

  const res = http.post("http://localhost:4000/notepads", payload, params);

  check(res, {
    "status is 202": (r) => r.status === 202,
  });
}