name: Notepad Service CI

on:
  push:
    branches: [main]
    paths:
      - "notepad-service/**"
  pull_request:
    branches: [main]
    paths:
      - "notepad-service/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        working-directory: ./notepad-service
        run: pnpm install --frozen-lockfile

      - name: Build TypeScript
        working-directory: ./notepad-service
        run: pnpm build

      - name: Build Docker image
        working-directory: ./notepad-service
        run: docker build -t microservice-queue-notepad-service:${{ github.sha }} .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag microservice-queue-user-service:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/microservice-queue-user-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/microservice-queue-user-service:latest